name: Promote build to qa

on:
  workflow_dispatch:

jobs:
  promote-build:
    runs-on: ubuntu-latest
    name: Promote build
    steps:
      - name: Git pull
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: npm script promote-build
        run: |
          git config user.email "gucci@vizlib.com"
          git config user.name "$GITHUB_ACTOR"
          npm version minor
      - name: Git push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN_FOR_PROTECTED }}
          tags: true
          branch: main

